baseURL = 'https://marg.es/on'
languageCode = 'en-us'
title = 'margeson@jack'
theme = 'risotto'

paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
sectionPagesMenu = "main"

[params]
noindex = false
math = false
  [params.theme]
  palette = "base16-dark"

  # Sidebar: about/bio
  [params.about]
  title = "Jack Margeson"
  description = "Student, software developer, and problem solver at heart. Welcome to my site!"
  # unicode/emoji logo:
  #logo = "🍚"
  # or use an image:
  logo_image = "android-chrome-512x512.png"

  # Sidebar: social links
  # Available icon sets:
  # * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
  # * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

  [[params.socialLinks]]
  icon = "fa-brands fa-github"
  title = "GitHub"
  url = "https://github.com/jack-margeson"

  [[params.socialLinks]]
  icon = "fa-brands fa-linkedin"
  title = "LinkedIn"
  url = "https://www.linkedin.com/in/jack-margeson/"

  [[params.socialLinks]]
  icon = "fa-solid fa-envelope"
  title = "Email"
  url = "mailto:margeson.jack@gmail.com"

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 9

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]
  # For hugo >= 0.60.0, enable inline HTML
  [markup.goldmark.renderer]
  unsafe = true

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true