[[redirects]]
  from = "https://marg.es"
  to = "https://marg.es/on/"
  status = 301
  force = true

[[redirects]]
  from = "https://git.marg.es"
  to = "https://github.com/jack-margeson"
  status = 301
  force = true
  
[[redirects]]
  from = "https://linkedin.marg.es"
  to = "https://www.linkedin.com/in/jack-margeson/"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self' data: 'unsafe-inline' 'unsafe-eval' *;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' *;
      style-src 'self' 'unsafe-inline' *;
    """

