[build]
  publish = "public"
  command = "hugo --gc --minify -b 'https://marg.es/on'"

  [build.environment]
    HUGO_VERSION = "0.124.1"

[context.production.environment]
  HUGO_ENV           = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $URL"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from   = "/"
  to     = "/on"
  status = 200